import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const policy = read("packages/policy/src/index.ts");
assert.match(policy,/feeQuoteHash/);
assert.match(policy,/deploymentId/);
assert.match(policy,/actorId/);
assert.match(policy,/organizationId/);
assert.match(policy,/QUOTE_TTL_TOO_LONG/);
assert.match(policy,/PWRC_BALANCE_IS_UTILITY_NOT_FINANCIAL_AUTHORITY/);
const bridge = read("packages/bridge/src/index.ts");
assert.match(bridge,/routeVersion/);
assert.match(bridge,/replayDomain/);
assert.match(bridge,/TRANSFER_REPLAY/);
assert.match(bridge,/verifyWrappedSupplyConservation/);
assert.match(bridge,/mintAllowed/);
const rewards = read("packages/rewards/src/index.ts");
assert.match(rewards,/EVIDENCE_ALREADY_REWARDED/);
assert.match(rewards,/ORGANIZATION_LIMIT_EXCEEDED/);
assert.match(rewards,/REWARD_UNDER_CHALLENGE/);
assert.match(rewards,/automaticMint: false/);
const fees = read("packages/fees/src/index.ts");
assert.match(fees,/SUCCESSFUL_POOL_PROCEEDS/);
assert.match(fees,/successCommissionChargedNowAtomic: 0n/);
assert.match(fees,/contributorChargeAtomic: 0n/);
assert.match(fees,/communityBps: 200/);
assert.match(fees,/ecosystemDevelopmentBps: 300/);
console.log("security and economic binding checks passed");
