"use client";
import { useCallback, useMemo, useState } from "react";
import type { PowerChainProviderStatus, SolanaAssetResponse, SolanaMarketResponse, SolanaOverview, SolanaProgramInfo } from "@powerchain/crisis-api-client";
import { powerChainApi } from "../lib/api";
import { usePollingResource } from "../hooks/use-polling-resource";
import { StatusBadge } from "./status-badge";

const compact=(value:string|null|undefined)=>value?`${value.slice(0,6)}…${value.slice(-6)}`:"—";
const number=(value:number|null|undefined,digits=2)=>value==null?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:digits}).format(value);
const when=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-US",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value)):"—";

export function SolanaOperationsConsole(){
  const overviewLoader=useCallback(()=>powerChainApi.solanaOverview(),[]);
  const programsLoader=useCallback(()=>powerChainApi.solanaPrograms(),[]);
  const providersLoader=useCallback(()=>powerChainApi.providerStatus(),[]);
  const sloLoader=useCallback(()=>powerChainApi.sloStatus(),[]);
  const overview=usePollingResource(overviewLoader,30_000,90_000);
  const programs=usePollingResource(programsLoader,60_000,180_000);
  const providers=usePollingResource(providersLoader,30_000,90_000);
  const slo=usePollingResource(sloLoader,30_000,90_000);
  const [mint,setMint]=useState(""); const [market,setMarket]=useState<SolanaMarketResponse|null>(null); const [asset,setAsset]=useState<SolanaAssetResponse|null>(null); const [lookupError,setLookupError]=useState<string|null>(null); const [looking,setLooking]=useState(false);
  const providerRows=useMemo(()=>Object.entries((market?.observations??[]).reduce<Record<string,string>>((acc,item)=>{acc[item.provider]=item.source.state;return acc;},{})),[market]);
  async function inspect(){const value=mint.trim();if(!value)return;setLooking(true);setLookupError(null);try{const [m,a]=await Promise.all([powerChainApi.solanaMarket(value),powerChainApi.solanaAsset(value)]);setMarket(m);setAsset(a);}catch(error){setLookupError(error instanceof Error?error.message:"Lookup failed");setMarket(null);setAsset(null);}finally{setLooking(false)}}
  return <div className="console-stack">
    <section className="panel" aria-labelledby="cluster-heading"><PanelHeader eyebrow="SOLANA CLUSTER" title="Network state" status={overview.data?.status} refreshing={overview.refreshing} onRefresh={()=>void overview.refresh()}/>
      {overview.error?<ResourceWarning error={overview.error} stale={overview.stale} failures={overview.failureCount}/>:null}
      {overview.loading&&!overview.data?<LoadingRows/>:<div className="metrics">
        <Metric label="Network" value={overview.data?.network??"—"}/><Metric label="Health" value={overview.data?.chain.health??"—"}/><Metric label="Slot" value={number(overview.data?.chain.slot,0)}/><Metric label="Block height" value={number(overview.data?.chain.blockHeight,0)}/><Metric label="Solana Core" value={overview.data?.chain.solanaCore??"—"}/><Metric label="Latest blockhash" value={compact(overview.data?.chain.blockhash)}/><Metric label="Epoch" value={number(overview.data?.chain.epoch,0)}/><Metric label="Last valid block" value={number(overview.data?.chain.lastValidBlockHeight,0)}/><Metric label="Genesis verification" value={overview.data?.clusterVerification.matchesExpected==null?"Not pinned":overview.data.clusterVerification.matchesExpected?"Matched":"Mismatch"}/>
      </div>}<p className="meta">Source: {overview.data?.source.provider??"waiting"} · refreshed {when(overview.updatedAt)}{overview.data?.source.latencyMs!=null?` · ${overview.data.source.latencyMs} ms`:""}{overview.stale?" · STALE SNAPSHOT":""}</p></section>

    <section className="panel" aria-labelledby="provider-heading"><PanelHeader eyebrow="DATA PROVIDERS" title="Provider health & provenance" status={providers.data?.status} refreshing={providers.refreshing} onRefresh={()=>void providers.refresh()}/>
      {providers.error?<ResourceWarning error={providers.error} stale={providers.stale} failures={providers.failureCount}/>:null}
      <div className="provider-health-grid">{(providers.data?.providers??[]).map((provider:PowerChainProviderStatus["providers"][number])=><article key={provider.provider} className="provider-health-card"><div><b>{provider.provider}</b><StatusBadge value={provider.state}/></div><span>{provider.capability.replaceAll("_"," ")}</span><dl><div><dt>Configured</dt><dd>{provider.configured?"Yes":"No"}</dd></div><div><dt>Fresh</dt><dd>{provider.configured?(provider.fresh?"Yes":"No"):"—"}</dd></div><div><dt>Age</dt><dd>{provider.ageSeconds==null?"—":`${provider.ageSeconds}s`}</dd></div><div><dt>Latency</dt><dd>{provider.latencyMs==null?"—":`${provider.latencyMs} ms`}</dd></div><div><dt>Last check</dt><dd>{when(provider.lastCheckedAt)}</dd></div><div><dt>Failures</dt><dd>{provider.consecutiveFailures}</dd></div></dl>{provider.lastErrorCode?<p>{provider.lastErrorCode}</p>:null}</article>)}</div>
      <p className="meta">Telemetry is redacted: provider credentials and upstream URLs never leave the backend. Market quorum: {providers.data?.summary.liveMarketProviders??0}/{providers.data?.summary.requiredQuorum??1} · raw {providers.data?.summary.rawQuorumMet?"MET":"NOT MET"} · effective {providers.data?.summary.quorumMet?"MET":"NOT MET"} · hysteresis {providers.data?.summary.failureHysteresis??"—"}/{providers.data?.summary.recoveryHysteresis??"—"} · RPC endpoints {providers.data?.rpc.endpointCount??0}, active {providers.data?.rpc.activeEndpointId??"—"} · cache {providers.data?.cache.entries??0}/{providers.data?.cache.inFlight??0}.</p>
    </section>

    <section className="panel" aria-labelledby="slo-heading"><PanelHeader eyebrow="SERVICE LEVEL" title="SLO & error budget" status={slo.data?.ok===true?"LIVE":slo.data?.evaluable?"DEGRADED":"UNKNOWN"} refreshing={slo.refreshing} onRefresh={()=>void slo.refresh()}/>
      {slo.error?<ResourceWarning error={slo.error} stale={slo.stale} failures={slo.failureCount}/>:null}
      <div className="metrics"><Metric label="Samples" value={`${slo.data?.sampleCount??0}/${slo.data?.minimumSamples??0}`}/><Metric label="Availability" value={slo.data?.availabilityPct==null?"—":`${number(slo.data.availabilityPct,3)}%`}/><Metric label="Availability target" value={slo.data?`${number(slo.data.availabilityTargetPct,3)}%`:"—"}/><Metric label="P95 latency" value={slo.data?.p95LatencyMs==null?"—":`${number(slo.data.p95LatencyMs,0)} ms`}/><Metric label="P95 target" value={slo.data?`${number(slo.data.p95TargetMs,0)} ms`:"—"}/><Metric label="Evaluation" value={!slo.data?.evaluable?"Warming up":slo.data.ok?"Within SLO":"Budget breached"}/></div>
      <p className="meta">Rolling {slo.data?.windowSeconds??"—"}s window · refreshed {when(slo.updatedAt)}. Health/readiness endpoints are excluded from the service-level sample set.</p>
    </section>

    <section className="panel" aria-labelledby="program-heading"><PanelHeader eyebrow="POWERCHAIN PROGRAMS" title="Deployment verification" status={programs.data?.status} refreshing={programs.refreshing} onRefresh={()=>void programs.refresh()}/>{programs.error?<ResourceWarning error={programs.error} stale={programs.stale} failures={programs.failureCount}/>:null}
      <div className="table-wrap"><table><thead><tr><th>Program</th><th>Family</th><th>Program ID</th><th>Status</th><th>Loader</th><th>Fingerprint</th><th>Upgrade authority</th><th>Executable</th></tr></thead><tbody>{(programs.data?.programs??[]).map((program:SolanaProgramInfo)=><tr key={program.slug}><td><b>{program.label}</b>{program.required?<small className="required-label">Required</small>:null}</td><td>{program.family}</td><td className="mono"><CopyValue value={program.programId}/></td><td><StatusBadge value={program.state}/></td><td>{program.loader??"—"}</td><td className="mono"><CopyValue value={program.deploymentFingerprintSha256}/></td><td className="mono"><CopyValue value={program.upgradeAuthority}/></td><td>{program.executable==null?"—":program.executable?"Yes":"No"}</td></tr>)}</tbody></table></div>
      <p className="meta">Verified {programs.data?.verification.verified??0} / configured {programs.data?.verification.configured??0} · required missing {programs.data?.verification.requiredMissing??0}.</p>
    </section>

    <section className="panel" aria-labelledby="asset-heading"><div className="panel-head"><div><span className="eyebrow">MINT INSPECTOR</span><h2 id="asset-heading">Supply, program, authorities and market</h2></div></div>
      <form className="mint-form" onSubmit={event=>{event.preventDefault();void inspect()}}><label><span>Solana mint address</span><input value={mint} onChange={event=>setMint(event.target.value)} autoComplete="off" spellCheck={false} inputMode="text" placeholder="Enter a 32-byte base58 mint"/></label><button type="submit" disabled={!mint.trim()||looking}>{looking?"Inspecting…":"Inspect mint"}</button></form>{lookupError?<p className="error" role="alert">{lookupError}</p>:null}
      {asset?<><div className="asset-title"><div><span className="eyebrow">{asset.symbol??asset.tokenProgramKind}</span><h3>{asset.name??compact(asset.mint)}</h3></div><CopyValue value={asset.mint} label="Copy mint"/></div><div className="metrics"><Metric label="Token program" value={asset.tokenProgramKind}/><Metric label="Supply" value={asset.uiAmountString??asset.supplyAtomic??"—"}/><Metric label="Decimals" value={asset.decimals==null?"—":String(asset.decimals)}/><Metric label="Mint authority" value={compact(asset.authorities.mintAuthority)}/><Metric label="Freeze authority" value={compact(asset.authorities.freezeAuthority)}/><Metric label="Extensions" value={asset.extensions.length?asset.extensions.map(item=>item.name).join(", "):"None reported"}/></div></>:null}
      {market?<><div className="market-grid"><div><span>USD price</span><b>${number(market.market.priceUsd,8)}</b></div><div><span>24h change</span><b>{market.market.change24hPct==null?"—":`${number(market.market.change24hPct,2)}%`}</b></div><div><span>Liquidity</span><b>{market.market.liquidityUsd==null?"—":`$${number(market.market.liquidityUsd,0)}`}</b></div><div><span>Primary provider</span><b>{market.primaryProvider}</b></div><div><span>Provider divergence</span><b>{market.divergenceBps==null?"—":`${market.divergenceBps} bps`}</b></div><div><span>Price block lag</span><b>{market.market.blockLag==null?"—":`${market.market.blockLag} slots`}</b></div><div><span>Market cap</span><b>{market.market.marketCapUsd==null?"—":`$${number(market.market.marketCapUsd,0)}`}</b></div><div><span>FDV</span><b>{market.derived.fullyDilutedValueUsd==null?"—":`$${number(market.derived.fullyDilutedValueUsd,0)}`}</b></div></div><p className="market-note"><StatusBadge value={market.status}/> Market data is for display and analytics only. On-chain supply and decimals remain RPC-authoritative.</p></>:null}
      {providerRows.length?<div className="provider-row">{providerRows.map(([provider,state])=><span key={provider}><b>{provider}</b><StatusBadge value={state}/></span>)}</div>:null}
    </section>
  </div>;
}

function PanelHeader({eyebrow,title,status,refreshing,onRefresh}:{eyebrow:string;title:string;status?:string|null;refreshing:boolean;onRefresh:()=>void}){return <div className="panel-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><div className="panel-actions"><StatusBadge value={status}/><button className="ghost-button" type="button" onClick={onRefresh} disabled={refreshing}>{refreshing?"Refreshing…":"Refresh"}</button></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><b title={value}>{value}</b></div>}
function ResourceWarning({error,stale,failures}:{error:string;stale:boolean;failures:number}){return <p className="error" role="status"><b>{stale?"Stale snapshot":"Refresh failed"}</b> · {error}{failures>1?` · ${failures} consecutive failures`:""}</p>}
function LoadingRows(){return <div className="loading-grid" aria-label="Loading network state">{Array.from({length:6},(_,i)=><span key={i}/>)}</div>}
function CopyValue({value,label="Copy"}:{value:string|null|undefined;label?:string}){const [copied,setCopied]=useState(false);if(!value)return <span>—</span>;return <button type="button" className="copy-button mono" title={value} onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}catch{}}}>{label==="Copy"?compact(value):label}{copied?" · Copied":""}</button>}
