import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { canonicalSha256 } from "./lib/release-integrity.mjs";
const root=resolve(new URL("..",import.meta.url).pathname);const base=(process.env.RELEASE_API_URL||"").replace(/\/$/,"");if(!base){console.error("RELEASE_API_URL is required");process.exit(1)}
const samples=Math.max(3,Number(process.env.RELEASE_CANARY_SAMPLES||6));const intervalMs=Math.max(0,Number(process.env.RELEASE_CANARY_INTERVAL_MS||1000));const minRatio=Math.min(1,Math.max(0.5,Number(process.env.RELEASE_CANARY_MIN_SUCCESS_RATIO||1)));const timeoutMs=Math.max(1000,Number(process.env.RELEASE_VERIFY_TIMEOUT_MS||12000));
const headers={accept:"application/json"};if(process.env.POWERCHAIN_INTERNAL_API_TOKEN?.trim())headers["x-powerchain-internal-token"]=process.env.POWERCHAIN_INTERNAL_API_TOKEN.trim();
async function get(path){const started=Date.now();try{const response=await fetch(`${base}${path}`,{headers,cache:"no-store",signal:AbortSignal.timeout(timeoutMs)});const text=await response.text();let body;try{body=JSON.parse(text)}catch{body={raw:text}}return{path,status:response.status,ok:response.ok,durationMs:Date.now()-started,body}}catch(error){return{path,status:0,ok:false,durationMs:Date.now()-started,error:error instanceof Error?error.message:String(error)}}}
const observations=[];let consecutiveFailures=0,maxConsecutiveFailures=0;for(let i=0;i<samples;i++){const rows=await Promise.all([get("/api/v1/solana/overview"),get("/api/v1/solana/programs"),get("/api/v1/providers/status")]);const ok=rows.every(row=>row.ok);consecutiveFailures=ok?0:consecutiveFailures+1;maxConsecutiveFailures=Math.max(maxConsecutiveFailures,consecutiveFailures);observations.push({index:i+1,checkedAt:new Date().toISOString(),ok,rows:rows.map(({body,...row})=>({...row,statusValue:body?.status??null}))});if(intervalMs&&i<samples-1)await new Promise(resolve=>setTimeout(resolve,intervalMs));}
const [slo,ready]=await Promise.all([get("/api/v1/observability/slo"),get("/api/v1/ready")]);const passed=observations.filter(item=>item.ok).length;const ratio=passed/observations.length;const failures=[];if(ratio<minRatio)failures.push(`canary success ratio ${ratio.toFixed(4)} < ${minRatio}`);if(maxConsecutiveFailures>Number(process.env.RELEASE_CANARY_MAX_CONSECUTIVE_FAILURES||0))failures.push(`canary consecutive failures ${maxConsecutiveFailures} exceeded limit`);if(!slo.ok||slo.body?.evaluable!==true||slo.body?.ok!==true)failures.push(`SLO gate not healthy/evaluable: HTTP ${slo.status}`);if(!ready.ok||ready.body?.ready!==true)failures.push(`final readiness did not pass: HTTP ${ready.status}`);
const report={schemaVersion:"1.0.0",releaseVersion:"1.0.0",checkedAt:new Date().toISOString(),apiBase:base,samples,passed,successRatio:ratio,minSuccessRatio:minRatio,maxConsecutiveFailures,observations,slo:slo.body??null,ready:ready.body??null,result:failures.length?"FAIL":"PASS",failures};report.integrity={algorithm:"sha256",payloadSha256:canonicalSha256(report)};mkdirSync(resolve(root,"release/evidence"),{recursive:true});writeFileSync(resolve(root,"release/evidence/canary-verification.json"),JSON.stringify(report,null,2)+"\n");if(failures.length){console.error("Canary verification failed:\n- "+failures.join("\n- "));process.exit(1)}console.log(`Canary verification passed (${passed}/${samples})`);
